const CATEGORIES = [['all','All'],['Beginner','Beginner'],['AI','AI'],['Development','Dev'],['Web','Web'],['Cloud','Cloud'],['Security','Security'],['Tools','Tools']];
let stories = []; let activeCategory = 'all';
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value='') => String(value).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const relativeTime = (date) => { const mins = Math.max(0, Math.floor((Date.now()-new Date(date).getTime())/60000)); if(mins<60)return `${mins}m`; const hours=Math.floor(mins/60); if(hours<24)return `${hours}h`; return `${Math.floor(hours/24)}d`; };
function renderNav(){ $('#categoryNav').innerHTML=CATEGORIES.map(([key,label])=>`<button class="chip ${key===activeCategory?'active':''}" data-category="${key}">${label}</button>`).join(''); document.querySelectorAll('.chip').forEach(b=>b.addEventListener('click',()=>{activeCategory=b.dataset.category;renderNav();renderFeed()})); }
function storyMarkup(item,index){return `<a class="top-story" href="${escapeHtml(item.url)}" target="_blank" rel="noopener"><span class="story-number">${String(index+1).padStart(2,'0')}</span><span class="story-title">${escapeHtml(item.title)}</span><span class="story-meta">${escapeHtml(item.source)} · ${relativeTime(item.published_at)}</span></a>`}
function cardMarkup(item){const social=item.type==='social';return `<article class="news-card"><a href="${escapeHtml(item.url)}" target="_blank" rel="noopener" aria-label="${escapeHtml(item.title)}"><div class="card-top"><span class="type-badge ${social?'social':''}">${social?'X POST':'ARTICLE'}</span><span>${escapeHtml(item.source)}</span><span>·</span><span>${relativeTime(item.published_at)}</span></div><h3 class="card-title">${escapeHtml(item.title)}</h3><p class="card-description">${escapeHtml(item.description||'')}</p><div class="card-footer"><span class="category-label">${escapeHtml(item.category)}</span><span class="open-label">${social?'投稿を見る':'記事'} ↗</span></div></a></article>`}
function visibleStories(){return activeCategory==='all'?stories:stories.filter(s=>s.category===activeCategory)}
function renderTop(){const top=stories.filter(s=>s.category==='Beginner'||s.beginner_score>=7).slice(0,5);$('#topStories').innerHTML=(top.length?top:stories.slice(0,5)).map(storyMarkup).join('')||'<div class="empty-state">ニュースを準備中です。</div>'}
function renderFeed(){const visible=visibleStories();$('#resultCount').textContent=`${visible.length} stories`;$('#newsList').innerHTML=visible.map(cardMarkup).join('');$('#emptyState').hidden=visible.length>0}
async function init(){renderNav();$('#newsList').innerHTML='<div class="skeleton"></div><div class="skeleton"></div>';try{const res=await fetch('data/news.json',{cache:'no-store'});if(!res.ok)throw new Error('news.json unavailable');const data=await res.json();stories=(Array.isArray(data)?data:data.items||[]).filter(x=>x.url&&x.title);stories.sort((a,b)=>(b.rank_score??b.beginner_score??0)-(a.rank_score??a.beginner_score??0));renderTop();renderFeed();const latest=stories[0]?.published_at;$('#updatedAt').textContent=latest?`Updated ${relativeTime(latest)} ago`:'Updated today';}catch(error){$('#topStories').innerHTML='<div class="empty-state">ニュースを読み込めませんでした。data/news.jsonを確認してください。</div>';$('#newsList').innerHTML='';$('#emptyState').hidden=false;$('#updatedAt').textContent='Offline';}}
init();
